version: "3.7"
services:
  app:
    build:
      args:
        user: felipe
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: serempre_laravel
    container_name: serempre_laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - serempre_laravel

  db:
    image: mysql:8
    container_name: serempre_laravel-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 30667:3306
    volumes:
      - dbdata_serempre:/var/lib/mysql
    networks:
      - serempre_laravel

  nginx:
    image: nginx:alpine
    container_name: serempre_laravel-nginx
    restart: unless-stopped
    ports:
      - 8099:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - serempre_laravel

networks:
  serempre_laravel:
    driver: bridge

volumes:
  dbdata_serempre:
    driver: local
